In [33]:
import pandas as pd
import numpy as np

In [34]:
data=pd.read_csv("sample_data_intw.csv",index_col=0)
data.head()

,label,msisdn,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,...,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90,pcircle,pdate
1,0,21408I70789,272.0,3055.050000,3065.150000,220.13,260.13,2.0,0.0,1539,...,6.0,0.0,2.0,12,6,0.0,29.000000,29.000000,UPW,2016-07-20
2,1,76462I70374,712.0,12122.000000,12124.750000,3691.26,3691.26,20.0,0.0,5787,...,12.0,0.0,1.0,12,12,0.0,0.000000,0.000000,UPW,2016-08-10
3,1,17943I70372,535.0,1398.000000,1398.000000,900.13,900.13,3.0,0.0,1539,...,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000,UPW,2016-08-19
4,1,55773I70781,241.0,21.228000,21.228000,159.42,159.42,41.0,0.0,947,...,6.0,0.0,2.0,12,6,0.0,0.000000,0.000000,UPW,2016-06-06
5,1,03813I82730,947.0,150.619333,150.619333,1098.90,1098.90,4.0,0.0,2309,...,6.0,0.0,7.0,42,6,0.0,2.333333,2.333333,UPW,2016-06-22

In [3]:
#! conda install xlrd

In [4]:
#pd.read_excel("Data_Description.xlsx")

In [5]:
#msisdn mobile number

In [6]:
data_sample=data#.sample(n=100,random_state=0)
data_sample.head()

,label,msisdn,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,...,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90,pcircle,pdate
1,0,21408I70789,272.0,3055.050000,3065.150000,220.13,260.13,2.0,0.0,1539,...,6.0,0.0,2.0,12,6,0.0,29.000000,29.000000,UPW,2016-07-20
2,1,76462I70374,712.0,12122.000000,12124.750000,3691.26,3691.26,20.0,0.0,5787,...,12.0,0.0,1.0,12,12,0.0,0.000000,0.000000,UPW,2016-08-10
3,1,17943I70372,535.0,1398.000000,1398.000000,900.13,900.13,3.0,0.0,1539,...,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000,UPW,2016-08-19
4,1,55773I70781,241.0,21.228000,21.228000,159.42,159.42,41.0,0.0,947,...,6.0,0.0,2.0,12,6,0.0,0.000000,0.000000,UPW,2016-06-06
5,1,03813I82730,947.0,150.619333,150.619333,1098.90,1098.90,4.0,0.0,2309,...,6.0,0.0,7.0,42,6,0.0,2.333333,2.333333,UPW,2016-06-22

In [7]:
data_sample.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 209593 entries, 1 to 209593
Data columns (total 36 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   label                 209593 non-null  int64
 1   msisdn                209593 non-null  object
 2   aon                   209593 non-null  float64
 3   daily_decr30          209593 non-null  float64
 4   daily_decr90          209593 non-null  float64
 5   rental30              209593 non-null  float64
 6   rental90              209593 non-null  float64
 7   last_rech_date_ma     209593 non-null  float64
 8   last_rech_date_da     209593 non-null  float64
 9   last_rech_amt_ma      209593 non-null  int64
 10  cnt_ma_rech30         209593 non-null  int64
 11  fr_ma_rech30          209593 non-null  float64
 12  sumamnt_ma_rech30     209593 non-null  float64
 13  medianamnt_ma_rech30  209593 non-null  float64
 14  medianmarechprebal30  209593 non-null  float64
 15  cnt_ma_rech90         209593 non-null  int64
 16  fr_ma_rech90          209593 non-null  int64
 17  sumamnt_ma_rech90     209593 non-null  int64
 18  medianamnt_ma_rech90  209593 non-null  float64
 19  medianmarechprebal90  209593 non-null  float64
 20  cnt_da_rech30         209593 non-null  float64
 21  fr_da_rech30          209593 non-null  float64
 22  cnt_da_rech90         209593 non-null  int64
 23  fr_da_rech90          209593 non-null  int64
 24  cnt_loans30           209593 non-null  int64
 25  amnt_loans30          209593 non-null  int64
 26  maxamnt_loans30       209593 non-null  float64
 27  medianamnt_loans30    209593 non-null  float64
 28  cnt_loans90           209593 non-null  float64
 29  amnt_loans90          209593 non-null  int64
 30  maxamnt_loans90       209593 non-null  int64
 31  medianamnt_loans90    209593 non-null  float64
 32  payback30             209593 non-null  float64
 33  payback90             209593 non-null  float64
 34  pcircle               209593 non-null  object
 35  pdate                 209593 non-null  object
dtypes: float64(21), int64(12), object(3)
memory usage: 59.2+ MB

In [8]:
data_sample.describe()

,label,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,cnt_ma_rech30,...,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90
count,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,...,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000,209593.000000
mean,0.875177,8112.343445,5381.402289,6082.515068,2692.581910,3483.406534,3755.847800,3712.202921,2064.452797,3.978057,...,2.758981,17.952021,274.658747,0.054029,18.520919,23.645398,6.703134,0.046077,3.398826,4.321485
std,0.330519,75696.082531,9220.623400,10918.812767,4308.586781,5770.461279,53905.892230,53374.833430,2370.786034,4.256090,...,2.554502,17.379741,4245.264648,0.218039,224.797423,26.469861,2.103864,0.200692,8.813729,10.308108
min,0.000000,-48.000000,-93.012667,-93.012667,-23737.140000,-24720.580000,-29.000000,-29.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,246.000000,42.440000,42.692000,280.420000,300.260000,1.000000,0.000000,770.000000,1.000000,...,1.000000,6.000000,6.000000,0.000000,1.000000,6.000000,6.000000,0.000000,0.000000,0.000000
50%,1.000000,527.000000,1469.175667,1500.000000,1083.570000,1334.000000,3.000000,0.000000,1539.000000,3.000000,...,2.000000,12.000000,6.000000,0.000000,2.000000,12.000000,6.000000,0.000000,0.000000,1.666667
75%,1.000000,982.000000,7244.000000,7802.790000,3356.940000,4201.790000,7.000000,0.000000,2309.000000,5.000000,...,4.000000,24.000000,6.000000,0.000000,5.000000,30.000000,6.000000,0.000000,3.750000,4.500000
max,1.000000,999860.755168,265926.000000,320630.000000,198926.110000,200148.110000,998650.377733,999171.809410,55000.000000,203.000000,...,50.000000,306.000000,99864.560864,3.000000,4997.517944,438.000000,12.000000,3.000000,171.500000,171.500000

In [9]:
data_sample.corr()

,label,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,cnt_ma_rech30,...,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90
label,1.000000,-0.003785,0.168298,0.166150,0.058085,0.075521,0.003728,0.001711,0.131804,0.237331,...,0.196283,0.197272,0.000248,0.044589,0.004733,0.199788,0.084144,0.035747,0.048336,0.049183
aon,-0.003785,1.000000,0.001104,0.000374,-0.000960,-0.000790,0.001692,-0.001693,0.004256,-0.003148,...,-0.001826,-0.001726,-0.002764,0.004664,-0.000611,-0.002319,-0.001191,0.002771,0.001940,0.002203
daily_decr30,0.168298,0.001104,1.000000,0.977704,0.442066,0.458977,0.000487,-0.001636,0.275837,0.451385,...,0.366116,0.471492,-0.000028,-0.011610,0.008962,0.563496,0.400199,-0.037305,0.026915,0.047175
daily_decr90,0.166150,0.000374,0.977704,1.000000,0.434685,0.471730,0.000908,-0.001886,0.264131,0.426707,...,0.340387,0.447869,0.000025,-0.005591,0.009446,0.567204,0.397251,-0.034686,0.019400,0.040800
rental30,0.058085,-0.000960,0.442066,0.434685,1.000000,0.955237,-0.001095,0.003261,0.127271,0.233343,...,0.180203,0.233453,-0.000864,-0.016482,0.004012,0.298943,0.234211,-0.035489,0.072974,0.095147
rental90,0.075521,-0.000790,0.458977,0.471730,0.955237,1.000000,-0.001688,0.002794,0.121416,0.230260,...,0.171595,0.231906,-0.001411,-0.009467,0.005141,0.327436,0.251029,-0.034122,0.067110,0.099501
last_rech_date_ma,0.003728,0.001692,0.000487,0.000908,-0.001095,-0.001688,1.000000,0.001790,-0.000147,0.004311,...,0.001193,0.000903,0.000928,0.001835,-0.000225,0.000870,-0.001123,0.002771,-0.002233,-0.001583
last_rech_date_da,0.001711,-0.001693,-0.001636,-0.001886,0.003261,0.002794,0.001790,1.000000,-0.000149,0.001549,...,0.000380,0.000536,0.000503,0.000061,-0.000972,0.000519,0.001524,-0.002239,0.000077,0.000417
last_rech_amt_ma,0.131804,0.004256,0.275837,0.264131,0.127271,0.121416,-0.000147,-0.000149,1.000000,-0.002662,...,-0.027612,0.008502,0.001000,0.028370,0.000093,0.014067,0.148460,0.021004,-0.027369,-0.014260
cnt_ma_rech30,0.237331,-0.003148,0.451385,0.426707,0.233343,0.230260,0.004311,0.001549,-0.002662,1.000000,...,0.765802,0.752296,0.000109,-0.067011,0.014703,0.685257,0.174104,-0.071451,0.043617,0.017362
fr_ma_rech30,0.001330,-0.001163,-0.000577,-0.000343,-0.001219,-0.000503,-0.001629,0.001158,0.002876,0.001669,...,0.002666,0.002470,-0.001100,-0.000331,0.003368,0.002634,-0.001890,-0.001292,0.001455,0.000998
sumamnt_ma_rech30,0.202828,0.000707,0.636536,0.603886,0.272649,0.259709,0.002105,0.000046,0.440821,0.656986,...,0.491864,0.531079,0.001633,-0.034460,0.009419,0.484761,0.257705,-0.042244,0.000112,-0.012596
medianamnt_ma_rech30,0.141490,0.004306,0.295356,0.282960,0.129853,0.120242,-0.001358,0.001037,0.794646,-0.011792,...,-0.029789,0.007125,0.001985,0.032477,-0.001143,0.014546,0.159613,0.022692,-0.018398,-0.002861
medianmarechprebal30,-0.004829,0.003930,-0.001153,-0.000746,-0.001415,-0.001237,0.004071,0.002849,-0.002342,0.000082,...,-0.000211,0.000134,-0.002176,-0.002289,0.001342,0.000736,-0.002141,-0.001927,0.001516,0.001811
cnt_ma_rech90,0.236392,-0.002725,0.587338,0.593069,0.312118,0.345293,0.004263,0.001272,0.016707,0.886433,...,0.689002,0.707558,-0.000573,-0.053637,0.015754,0.783419,0.244602,-0.072481,0.011943,-0.003141
fr_ma_rech90,0.084385,0.004401,-0.078299,-0.079530,-0.033530,-0.036524,0.001414,0.000798,0.106267,-0.152759,...,-0.119083,-0.123664,0.001635,0.020626,-0.002756,-0.132035,-0.045780,0.016964,0.036817,0.077529
sumamnt_ma_rech90,0.205793,0.001011,0.762981,0.768817,0.342306,0.360601,0.002243,-0.000414,0.418735,0.584060,...,0.442766,0.508599,0.001152,-0.022133,0.011306,0.562609,0.321739,-0.042386,-0.026409,-0.029997
medianamnt_ma_rech90,0.120855,0.004909,0.257847,0.250518,0.110356,0.103151,-0.000726,0.000219,0.818734,-0.051347,...,-0.060766,-0.025307,0.001016,0.036475,-0.000123,-0.023450,0.134139,0.031696,-0.035640,-0.023022
medianmarechprebal90,0.039300,-0.000859,0.037495,0.036382,0.027170,0.029547,-0.001086,0.004158,0.124646,0.013463,...,-0.043381,-0.033878,0.001884,0.030534,-0.000926,-0.036412,0.027130,0.032453,-0.031760,-0.031210
cnt_da_rech30,0.003827,0.001564,0.000700,0.000661,-0.001105,-0.000548,-0.003467,-0.003628,-0.001837,0.002306,...,0.001852,0.001487,-0.000394,0.000049,-0.001986,0.003369,-0.000647,-0.001365,-0.000471,0.000382
fr_da_rech30,-0.000027,0.000892,-0.001499,-0.001570,-0.002558,-0.002345,-0.003626,-0.000074,-0.003230,-0.002732,...,-0.003212,-0.003395,-0.001070,-0.001141,-0.001623,-0.001593,-0.001069,-0.001623,0.001709,-0.000725
cnt_da_rech90,0.002999,0.001121,0.038814,0.031155,0.072255,0.056282,-0.003538,-0.001859,0.014779,0.011981,...,0.017976,0.026249,-0.001855,-0.003351,0.000907,0.020909,0.038019,-0.003094,0.013430,0.024046
fr_da_rech90,-0.005418,0.005395,0.020673,0.016437,0.046761,0.036886,-0.002395,-0.000203,0.016042,0.006989,...,0.010021,0.014935,-0.000754,-0.002234,0.001993,0.011501,0.021785,-0.000949,0.000354,0.001226
cnt_loans30,0.196283,-0.001826,0.366116,0.340387,0.180203,0.171595,0.001193,0.000380,-0.027612,0.765802,...,1.000000,0.957742,0.000251,-0.093146,0.015595,0.852905,0.143590,-0.097871,0.067842,0.033369
amnt_loans30,0.197272,-0.001726,0.471492,0.447869,0.233453,0.231906,0.000903,0.000536,0.008502,0.752296,...,0.957742,1.000000,-0.000073,-0.078531,0.014625,0.897961,0.329170,-0.087989,0.060425,0.030901
maxamnt_loans30,0.000248,-0.002764,-0.000028,0.000025,-0.000864,-0.001411,0.000928,0.000503,0.001000,0.000109,...,0.000251,-0.000073,1.000000,0.007782,0.003987,-0.001850,-0.000487,0.009330,-0.001512,-0.000915
medianamnt_loans30,0.044589,0.004664,-0.011610,-0.005591,-0.016482,-0.009467,0.001835,0.000061,0.028370,-0.067011,...,-0.093146,-0.078531,0.007782,1.000000,-0.003670,-0.067580,0.058378,0.911604,-0.006007,0.003178
cnt_loans90,0.004733,-0.000611,0.008962,0.009446,0.004012,0.005141,-0.000225,-0.000972,0.000093,0.014703,...,0.015595,0.014625,0.003987,-0.003670,1.000000,0.017697,0.001450,-0.002571,0.000587,-0.000476
amnt_loans90,0.199788,-0.002319,0.563496,0.567204,0.298943,0.327436,0.000870,0.000519,0.014067,0.685257,...,0.852905,0.897961,-0.001850,-0.067580,0.017697,1.000000,0.323417,-0.095160,0.052142,0.029653
maxamnt_loans90,0.084144,-0.001191,0.400199,0.397251,0.234211,0.251029,-0.001123,0.001524,0.148460,0.174104,...,0.143590,0.329170,-0.000487,0.058378,0.001450,0.323417,1.000000,0.032256,0.013376,0.029679
medianamnt_loans90,0.035747,0.002771,-0.037305,-0.034686,-0.035489,-0.034122,0.002771,-0.002239,0.021004,-0.071451,...,-0.097871,-0.087989,0.009330,0.911604,-0.002571,-0.095160,0.032256,1.000000,-0.013388,-0.010443
payback30,0.048336,0.001940,0.026915,0.019400,0.072974,0.067110,-0.002233,0.000077,-0.027369,0.043617,...,0.067842,0.060425,-0.001512,-0.006007,0.000587,0.052142,0.013376,-0.013388,1.000000,0.830363
payback90,0.049183,0.002203,0.047175,0.040800,0.095147,0.099501,-0.001583,0.000417,-0.014260,0.017362,...,0.033369,0.030901,-0.000915,0.003178,-0.000476,0.029653,0.029679,-0.010443,0.830363,1.000000

In [10]:
data_sample.drop(columns=["pdate","msisdn","pcircle"],inplace=True)
data_sample.head()

,label,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,cnt_ma_rech30,...,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90
1,0,272.0,3055.050000,3065.150000,220.13,260.13,2.0,0.0,1539,2,...,2,12,6.0,0.0,2.0,12,6,0.0,29.000000,29.000000
2,1,712.0,12122.000000,12124.750000,3691.26,3691.26,20.0,0.0,5787,1,...,1,12,12.0,0.0,1.0,12,12,0.0,0.000000,0.000000
3,1,535.0,1398.000000,1398.000000,900.13,900.13,3.0,0.0,1539,1,...,1,6,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000
4,1,241.0,21.228000,21.228000,159.42,159.42,41.0,0.0,947,0,...,2,12,6.0,0.0,2.0,12,6,0.0,0.000000,0.000000
5,1,947.0,150.619333,150.619333,1098.90,1098.90,4.0,0.0,2309,7,...,7,42,6.0,0.0,7.0,42,6,0.0,2.333333,2.333333

In [11]:
#data_target
y=data_sample["label"].values
y

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [12]:
data_sample.drop(columns="label",inplace=True)

In [13]:
X=data_sample
X.head()

,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,cnt_ma_rech30,fr_ma_rech30,...,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90
1,272.0,3055.050000,3065.150000,220.13,260.13,2.0,0.0,1539,2,21.0,...,2,12,6.0,0.0,2.0,12,6,0.0,29.000000,29.000000
2,712.0,12122.000000,12124.750000,3691.26,3691.26,20.0,0.0,5787,1,0.0,...,1,12,12.0,0.0,1.0,12,12,0.0,0.000000,0.000000
3,535.0,1398.000000,1398.000000,900.13,900.13,3.0,0.0,1539,1,0.0,...,1,6,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000
4,241.0,21.228000,21.228000,159.42,159.42,41.0,0.0,947,0,0.0,...,2,12,6.0,0.0,2.0,12,6,0.0,0.000000,0.000000
5,947.0,150.619333,150.619333,1098.90,1098.90,4.0,0.0,2309,7,2.0,...,7,42,6.0,0.0,7.0,42,6,0.0,2.333333,2.333333

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.30,random_state=0)

In [16]:
X_train.head()

,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,cnt_ma_rech30,fr_ma_rech30,...,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90
102661,965.0,6056.670000,9096.670,16299.81,24491.63,17.0,0.0,4048,1,0.0,...,1,12,12.0,0.0,1.0,12,12,0.0,0.0,0.0
203697,562.0,2407.233333,2415.500,5125.74,6284.14,1.0,0.0,770,3,16.0,...,4,24,6.0,0.0,6.0,36,6,0.0,8.0,5.6
104429,1104.0,33614.000000,34674.810,3938.25,4512.45,2.0,0.0,770,5,10.0,...,5,48,12.0,0.0,7.0,60,12,0.0,3.0,2.5
105387,778.0,7975.000000,11329.000,1199.79,2493.18,1.0,0.0,2309,4,14.0,...,0,0,0.0,0.0,0.0,0,0,0.0,0.0,117.0
93755,374.0,42.765000,42.765,90.00,90.00,17.0,0.0,2320,1,0.0,...,1,6,6.0,0.0,1.0,6,6,0.0,0.0,0.0

In [17]:
X_train.shape

(146715, 32)

In [18]:
X_test.shape

(62878, 32)

In [19]:
X_train.size

4694880

In [20]:
X_train.ndim

2

In [21]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [22]:
rfc=RandomForestClassifier(n_estimators=100,random_state=10)

In [23]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=10, verbose=0,
                       warm_start=False)

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
y_pred=rfc.predict(X_test)

In [26]:
accuracy_score(y_test,y_pred)*100

91.16861223321352

Cross Validation

In [29]:
from sklearn.model_selection import cross_val_score

In [35]:
data_10k=data.sample(n=10000,random_state=0)

In [36]:
data_10k.head()

,label,msisdn,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,...,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90,pcircle,pdate
23413,1,90231I82730,1239.0,5762.280,5803.80,725.38,879.10,1.0,0.0,773,...,6.0,0.0,13.0,78,6,0.0,2.818182,4.769231,UPW,2016-07-12
106458,1,20697I70780,607.0,12325.978,12365.89,952.44,1961.88,13.0,0.0,3178,...,12.0,0.0,1.0,12,12,0.0,0.000000,0.000000,UPW,2016-07-24
160065,0,95312I85339,417.0,1200.000,1200.00,96.56,96.56,2.0,0.0,773,...,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000,UPW,2016-07-18
46826,1,12401I88659,300.0,850.000,1600.00,869.56,969.12,32.0,0.0,770,...,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000,UPW,2016-08-10
86928,0,68367I84458,977.0,6545.322,6601.69,612.39,740.39,14.0,0.0,1539,...,6.0,0.5,7.0,42,6,0.0,2.000000,2.428571,UPW,2016-07-16

In [45]:
y_=data_10k.iloc[:,0].values
X_=data_10k.iloc[:,1:]#.drop(columns=["pdate","msisdn","pcircle"],inplace=True)

In [46]:
X_.drop(columns=["pdate","msisdn","pcircle"],inplace=True)
X_.head()

,aon,daily_decr30,daily_decr90,rental30,rental90,last_rech_date_ma,last_rech_date_da,last_rech_amt_ma,cnt_ma_rech30,fr_ma_rech30,...,cnt_loans30,amnt_loans30,maxamnt_loans30,medianamnt_loans30,cnt_loans90,amnt_loans90,maxamnt_loans90,medianamnt_loans90,payback30,payback90
23413,1239.0,5762.280,5803.80,725.38,879.10,1.0,0.0,773,15,1.0,...,12,72,6.0,0.0,13.0,78,6,0.0,2.818182,4.769231
106458,607.0,12325.978,12365.89,952.44,1961.88,13.0,0.0,3178,4,4.0,...,1,12,12.0,0.0,1.0,12,12,0.0,0.000000,0.000000
160065,417.0,1200.000,1200.00,96.56,96.56,2.0,0.0,773,1,0.0,...,1,6,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000
46826,300.0,850.000,1600.00,869.56,969.12,32.0,0.0,770,0,0.0,...,1,6,6.0,0.0,1.0,6,6,0.0,0.000000,0.000000
86928,977.0,6545.322,6601.69,612.39,740.39,14.0,0.0,1539,3,11.0,...,4,24,6.0,0.5,7.0,42,6,0.0,2.000000,2.428571

In [47]:
x_train,x_test,y_train_,y_test_=train_test_split(X_,y_,test_size=.30,random_state=42)

In [48]:
score=cross_val_score(rfc,x_train,y_train_,cv=10)

In [49]:
score

array([0.91142857, 0.91571429, 0.90285714, 0.89428571, 0.91142857,
       0.91285714, 0.92428571, 0.91428571, 0.90714286, 0.91285714])

In [50]:
score.mean()

0.9107142857142858

In [51]:
score.max()

0.9242857142857143

In [52]:
score.min()

0.8942857142857142

As due to big size my system is hangging taking sample

In [53]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [54]:
# Voting Classifier - Multiple Model Ensemble 

#lr = LogisticRegression()
#lr STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
nb=GaussianNB()
dt = DecisionTreeClassifier()
svm = SVC(kernel = 'poly', degree = 2 )

In [55]:
evc = VotingClassifier( estimators= [('nb',nb),('dt',dt),('svm',svm)])
#default voting ="hard"

In [56]:
evc.fit(x_train,y_train_)

VotingClassifier(estimators=[('nb',
                              GaussianNB(priors=None, var_smoothing=1e-09)),
                             ('dt',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort='deprecated',
                                                     random_state=None,
                                                     splitter='best')),
                             ('svm',
                              SVC(C=1.0, break_ties=False, cache_size=200,
                                  class_weight=None, coef0=0.0,
                                  decision_function_shape='ovr', degree=2,
                                  gamma='scale', kernel='poly', max_iter=-1,
                                  probability=False, random_state=None,
                                  shrinking=True, tol=0.001, verbose=False))],
                 flatten_transform=True, n_jobs=None, voting='hard',
                 weights=None)

In [57]:
evc.score(x_test,y_test_)

0.8713333333333333

#### Thank You